{% set package = "ucsc-fatotwobit" %}
{% set program = "fatotwobit" %}
{% set version = "457" %}
{% set sha256 = "fa52259d4998fea75555fe7952c79d2f9a572e3be52a4274e6bb2db706d152fc" %}

package:
  name: {{ package }}
  version: {{ version }}

source:
  url: "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.archive/userApps.v{{ version }}.src.tgz"
  sha256: {{ sha256 }}
#  patches:
#    - "include.patch"


build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - libpng
    - libuuid
    - mysql-connector-c
    - openssl
    - libopenssl-static
    - zlib
  run:
    - libpng
    - libuuid
    - mysql-connector-c
    - openssl

test:
  commands:
    # just check for existence, because the individual packages have no unified behavior
    - which {{ program }}

about:
  home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
  license: "varies; see http://genome.ucsc.edu/license"
  summary: "Convert all or part of .2bit file to fasta"
