{% set version = "2.5.1" %}
{% set sha256 = "05400437cf15595e10b1a25df6c9c48856f356130f9d1e380fa8866b6d27f457" %}

package:
  name: viennarna
  version: {{ version }}

build:
  number: 0
  run_exports:
    # Ronny said VRNA is stable in x.x releases
    - {{ pin_subpackage('viennarna', max_pin='x.x') }}

source:
  url: https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_5_x/ViennaRNA-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl=5.32.1
    - python=3.10.8
    - mpfr
#    - clang
#    - clangxx
#    - pkgconfig ## needed for viennarna version checks in dependent packages
#    - bzip2
#    - clang=16.0.1
#    - libclang
#    - clangxx
#    - gfortran
#    - openssl
#    - libopenssl-static
#    - zlib
#    - libpng
#    - libuuid
#    - libedit
#    - libevent
#    - make
#    - libpng
#    - libuuid
#    - mysql-connector-c
#    - openssl
#    - libopenssl-static
#    - zlib
#    - llvm-openmp
#    - dlib
  run:
    - python
#    - llvm-openmp

test:
  commands:
    - RNAalifold --version
    - RNAeval    --version
    - RNAfold    --version
    - RNAplfold  --version
    - RNAsubopt  --version
    - RNAlocmin  --version
    - kinwalker  --help >& /dev/null

about:
  home: http://www.tbi.univie.ac.at/RNA/
  license: custom
  license_file: COPYING
  summary: Vienna RNA package -- RNA secondary structure prediction and comparison
