name: Build Conda Package

on:
  push:
    branches:
      - main
    paths:
      - 'recipes/**'
  pull_request:
    branches:
      - main
    paths:
      - 'recipes/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Conda Package on macOS Intel
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
#        recipe: [ 'b2ct', 'ct2out', 'ucsc-blat', 'ucsc-fatotwobit', 'ucsc-twobitinfo', 'ucsc-twobittofa', 'viennarna' ]
        recipe: [ 'b2ct']

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
#          miniconda-version: "latest"
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: 3.9
          channels: conda-forge,anaconda
          channel-priority: strict

      - name: Install conda build
        shell: bash -l {0}
        run: mamba install conda-build

      - name: Install anaconda-client
        shell: bash -l {0}
        run: mamba install anaconda-client

      - name: test anaconda-client
        shell: bash -l {0}
        run: anaconda --help

      - name: Conda Info
        shell: bash -l {0}
        run: conda info

      - name: Build Conda Package
        shell: bash -l {0}
        run: conda build recipes/${{ matrix.recipe }}/

      # Optional: If you want to keep the built packages as artifacts, add this step
      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: conda-packages
          path: $(conda info --root)/envs/test/conda-bld/osx-64/*.tar.bz2

      - name: Upload Conda Package
        if: success() && github.ref == 'refs/heads/main'
        shell: bash -l {0}
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload $(conda info --root)/envs/test/conda-bld/osx-64/*.tar.bz2 --force
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

      - name: Install package
        if: ${{ matrix.recipe }} == 'b2ct'
        shell: bash -l {0}
        run: conda create -n b2ct

      - name: Install package
        if: ${{ matrix.recipe }} == 'b2ct'
        shell: bash -l {0}
        run: conda activate b2ct

      - name: Install package
        if: ${{ matrix.recipe }} == 'b2ct'
        shell: bash -l {0}
        run: conda install jcheneby::b2ct

#      - name: Test architecture
#        if: ${{ matrix.recipe }} == 'b2ct'
#        shell: bash -l {0}
#        run: lipo -info $(where b2ct)

      - name: Test package
        if: ${{ matrix.recipe }} == 'b2ct'
        shell: bash -l {0}
        run: b2ct < recipes/b2ct/stub_known_pri_fold_minus.rnafold.filtered
